### ISSUE TITLE
Custom text on non ECC car

### ISSUE THREAD

**Issue by obertr0n** [Trueffelwurm/Car-CAN-Message-DB#3]
Hi, do you know a method to add custom text on a GID & CD30 MP3 without ECC (electronic climate control) in the filed designated to show the current setting for ECC?
![gid_ecc](https://user-images.githubusercontent.com/10163987/36118386-8a014266-1045-11e8-857e-ded7d1208655.png)

**Comment by JJToB** [comment]
Hi, that SHOULD be possible by sending an A0 package to the display, containing a 0A23 message.
I don't know how many characters the field can handle, it's probably limited to 3 chars.

You have to enable the ECC option in your GID via Tech2 to activate the ECC-Field in the display.

**Comment by obertr0n** [comment]
Thank you for your reply. I enabled the ECC in the variant configuration of the GID, and now I have the border, without any information (doh).
I think I will also have to enable it in the CAN configuration.

Do you have a message dump example for that section? So I have an idea how the data is packed? It's the same packing as described above (ISO-15765-2)?
Thank you for your willingness to help.

**Comment by JJToB** [comment]
Sure, here is an example:

```  
  can0  6C8   [8]  10 1E C0 00 1B 0A 23 03
  can0  2C8   [8]  30 00 00 00 00 00 00 00
  can0  6C8   [8]  21 00 32 00 31 00 B0 24
  can0  6C8   [8]  22 01 E0 59 25 03 00 45
  can0  6C8   [8]  23 00 63 00 6F 26 02 E0
  can0  6C8   [8]  24 50 00 41 6F 26 02 E0
```

It sends the follwoing values:
23 (Temperature): "21°"
24 (Position): 0xE059 (some seat-icon)
25 (Mode): "Eco"
26 (Level): 0xE050 (fan-icon) + "A"

**Comment by obertr0n** [comment]
Thank you for your fast reply, unfortunately I don't quite get how this should work, since this doesn't match the info form the Info-Display.md.
0x6C8 is the ID of the message sent from ECC?
0x2C8 is the ID for what exactly?
Sorry if I get annoying. (If you think it's faster to exchange information in other manner, I'm open to suggestions)

**Comment by JJToB** [comment]
I'm very sorry, the first line of the dump got cut off due to wrong markdown usage. I just corrected that.
0x06C8 is the ID of the message to the DIS, 0x02C8 is the reply that confirms the readiness of receiving a multi packet message.
The first Byte of all packages is the control-structure for the multi packet messages and is  not part of the message itself.

**Comment by obertr0n** [comment]
Thank you! I will give it a try once I get home from work.
Basically I have to send `10 1E C0 00 1B 0A 23 03` wait for the response on `0x02C8`
and then send the rest of the message.

Another thing that I noticed is that if I send a message on the `0x06C1` ID to the info display using the correct format, after some time the display will reboot, or shutdown itself. Have you experienced this?

**Comment by obertr0n** [comment]
Hello again, I think I'm a bit stuck. I can't figure out why the text won't show up on that field of the GID.

> Hi, that SHOULD be possible by sending an A0 package to the display, containing a 0A23 message.

I don't get he part with A0 package, could you please provide more informations on that?
On another point, it seems that your website is down.
Have a nice day!

**Comment by JJToB** [comment]
Hi, sorry for the late answer!

I just tried to send text to the A/C-Field, here is the result:

![img_20180309_155433056_hdr](https://user-images.githubusercontent.com/6707236/37213985-e69dcc48-23b3-11e8-8aeb-f916a859aceb.jpg)

The message I sent looks like this:
```
28 C0 00 25 0A 
   23 03
      00 61 00 62 00 63
   24 04
      00 64 00 65 00 66 00 67
   25 03
      00 68 00 69 00 6A
   26 03
      00 6B 00 6C 00 6D
```

And these are the actual packages:
```
cansend can0 6C8#10.26.C0.00.23.0A.23.03
cansend can0 6C8#21.00.61.00.62.00.63.24
cansend can0 6C8#22.04.00.64.00.65.00.66
cansend can0 6C8#23.00.67.25.03.00.68.00
cansend can0 6C8#24.69.00.6A.26.03.00.6B
cansend can0 6C8#25.00.6C.00.6D.00.6E.00
```

All fields accept three chars, except the airflow-mode (0x24) which takes four chars.

Hope this helps!

Edit:
I always send all packets directly in a row without waiting for `2C8#30...` confirmation when testing things. The bus is not very busy and the worst thing i can imagine is corrupting an update to the display...

**Comment by obertr0n** [comment]
Hello, no worries.
Thank you for the reply. I managed to figure this out.
My test bench is on my desk, where I have the HU and the Display.
And the thing I was doing wrong is that the message is visible only if the ignition signal is present.

Did you managed to find the ID for windows controls?

**Comment by megadrifter** [comment]
Will there be a conflict if I send some data while the system also does so? Who's message will be stronger?

**Comment by obertr0n** [comment]
The lower the ID the more priority has the message. This is the arbitration made on bus.
The way how the messages are sent to the screen, is written in this pages (ISO-TP).
IF other ECUs send the data over the same message ID, and follow a protocol like ISO TP, you might break the information that other ECUs try to send. 
PS: Correct me if I'm wrong.

**Comment by JJToB** [comment]
That is (to my understanding) totally correct. But the only Information which are sent in multiframes (ISO-TP) are Phone/AC/Radio data for the display. So there won't break something if that information gets corrupted. The only risc I can see is getting some weird text on the display.
That, of course, only applies to the MS-CAN bus!
You don't want to mess with the HS-CAN bus, especially while driving!!!

I didn't find the window control IDs, but I really was digging only in the MS-CAN bus. The window controls should be on single wire.

Also, I am not sure about the ignition for the A/C display. My first attempts did not show anything until I turned on the ignition. But I still was able to send data after turning the ignition off.

**Comment by megadrifter** [comment]
There is NO windows control in the bus, sorry, you should live with this.

**Comment by obertr0n** [comment]
@Trueffelwurm The thing with the ignition is pretty tested on my side. If the ign signal is not present at the beginning of the transmission at least, the message won't show on screen.

I have another question if possible: On my GID only the first row is usable, and I tried to send as much characters as possible, but it seems to be limited to 14, even if when playing a melody from CD it show 20+ chars. Do you know something about a GM protocol related to this?

**Comment by JJToB** [comment]
I don't know about any limits in the protocol, but i assume it is identical to the one used on the color display.
I can send as much characters as the display can show (the lines run out the right side of the display), wich are more than 14.
So I thin that limitation might be a display limit of the GID.

**Comment by obertr0n** [comment]
@Trueffelwurm I think it was a problem with my message sending procedure. I included also the preamble that seems contain some information about formatting the text and it seems to be working.

I have another question (I know, I ask a lot of questions :D ):
I noticed that you discovered some information about the RPM, engine temp and vehicle speed (0x04E8, 0x04EC).
How can this info be interpreted? I don't get the computation that should be made. Could you please give a sort example (PS. I cannot interrogate the ECC for the info)?

**Comment by obertr0n** [comment]
Hi there, do you have somehow any info on the above question?

**Comment by JJToB** [comment]
Hey, sorry again for the late answer!

The Information in the table above was somehow kind off wierd when it's actually so simple:

`4E8#46:0F:0C:50:19:0A:02`
Byte 3+4 is: `0x0C50` = **3152 RPM**
Bzte 5 is `0x19` = **25 km/h**

The Temperature is just a little more complicated, the value is shifted by 40 to be able to display negative values:
`4EC#46:07:3C:29:00`
Byte 3 is `0x3C` = 60 -> *60-40* = **20°C**

You might be able to send diagnostic requests to the ECC to ask for that values but my intention was to be as quiet as possible on the bus.

**Comment by obertr0n** [comment]
thank you for the clarifications :)
I managed to decode the data, my plan was to display it on the "empty" ECC line on my GID.
Unfortunately, when testing in the car, with or without the engine running, the message won't show..
The same behavior can be observed as in one of the above messages:
If I send the message:
`0x0698:0x48, 0x00, 0x60, 0x02, 0x82, 0x00, 0x4, 0x00` then the data will be shown.
Do you have any idea or suggestion?

**Comment by obertr0n** [comment]
Thank you for your time and comments, very helpful 👍

**Comment by lukyanov96** [comment]
@Trueffelwurm Hi. Can you help me? You wrote information about Tech2 in your database on GoogleDocs. We send first line in SW-Can, and we must receive next message. Do I understand correctly?
![image](https://user-images.githubusercontent.com/36925011/45300817-0a36b480-b518-11e8-8f5b-b3e18a5b2e08.png)

**Comment by obertr0n** [comment]
@lukyanov96  Hello, I think you are on the wrong bus. From what I understand the ID 0x248 is used for diagnostic reply from ECC. Since ECC is on MS-CAN, I would suggest to use the MS-CAN, not SW-CAN.
